### ISSUE TITLE
Type 'DataErrorInfoAdapter' is not defined

### ISSUE THREAD

**Issue by maciz84** [pglazkov/MvvmValidation#12]
In version 3.0.0 the error **Type 'DataErrorInfoAdapter' is not defined** shows up but not in v2.0.2?

**Comment by maciz84** [comment]
Is this a bug or some new changes that I don't know about?

**Comment by pglazkov** [comment]
`DataErrorInfoAdapter` has been deprecated and removed from the library because the `IDataErrorInfo` interface is not supported in platforms other than full .NET, more specifically it is not supported in .NET Standard that the library is build on. However, there is another newer interface that has the same functionality but a bit more flexible: `INotifyDataErrorInfo`. You can find an example how to use the `NotifyDataErrorInfoAdapter` here: https://github.com/pglazkov/MvvmValidation/blob/master/Examples/FormValidationExample/Infrastructure/ValidatableViewModelBase.cs

If case you still want to continue using `IDataErrorInfo` and `DataErrorInfoAdapter`, you can just copy the implementation of that class to your solution from the earlier version of the library, it is pretty simple: https://github.com/pglazkov/MvvmValidation/blob/releases/2.0/MvvmValidation/DataErrorInfoAdapter.cs
