### ISSUE TITLE
Compilation fails in Visual Studio for Mac

### ISSUE THREAD

**Issue by EltonGarcia** [pglazkov/MvvmValidation#13]
Compilation in Visual Studio for Mac fails with the message: The type or namespace name 'MvvmValidation' could not be found (are you missing a using directive or an assembly reference?)

After opening the same project and build in Xamarin Studio it works perfectly.

Related: https://stackoverflow.com/a/41591578/2364774

**Comment by vickieallen** [comment]
I have the same issue - I think this is due to the target framework for compilation being 5, even though the min req is 1. I've had to downgrade our version of the package in Nuget to 2.0.2 and now it builds fine in Visual Studio 2015, whereas before it would only build in 2017. 
![image](https://user-images.githubusercontent.com/5023006/28828081-8c00c2fc-76c7-11e7-980a-a23b2024e976.png)

**Comment by pglazkov** [comment]
The library is compiled against .NET Standard 1.0. Please make sure that your target platform is supported by .NET Standard 1.0. You can refer to the table here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard.
