### ISSUE TITLE
How to do Validation during Propoerty Set

### ISSUE THREAD

**Issue by disklosr** [pglazkov/mvvmvalidation#2]
I'm interested in using this library as an implementation for INotifyDataErrorInfo interface. And I want to run validation each time I set a propoerty. Problem is that the Validate() method in this library expects an expression as an input, while I need an overload of it that accepts a string instead. This prevents me from using it inside my generic setter:

```csharp
protected virtual void SetValue<T>(ref T field, T val, [CallerMemberName] string propertyName = null, Action onValueChanged = null)
{
    if (EqualityComparer<T>.Default.Equals(field, val))
        return;

    field = val;
    RaisePropertyChanged(propertyName);
    //Need to add validator.Validate(propertyName) here but can't because my param is a string
    onValueChanged?.Invoke();
}
```

Do you have any workaround for this or another approach of executing validation during set? Thanks.

**Comment by pglazkov** [comment]
There is an overload of the `Validate` method that takes `object` as the argument. You can use that. This code should compile:

    validator.Validate(propertyName);

**Comment by disklosr** [comment]
Great, exactly what I need.
I also noticed the NotifyDataErrorInfoAdapter type isn't included in the nuget package. When are you planning to update it?

**Comment by pglazkov** [comment]
It is included in the portable version of the library, but for some reason NuGet downloads the .NET 4.0 version that doesn't include it (because .NET 4.0 doesn't have the INotifyDataErrorInfo interface). I will look into that. 

In the meanwhile you could download the binaries of the library from CodePlex and reference the portable library manually without using NuGet. I will try to update NuGet packages ASAP. 

Sorry for the inconvenience and thanks for your feedback!

**Comment by disklosr** [comment]
I'll wait for you to update the nuget package as I don't like referencing binaries directly.

Let me know when you update it. Thanks a lot for your quick support.

**Comment by pglazkov** [comment]
Fixed the NuGet package for .NET 4.5. You can try it by installing a pre-release version from NuGet: https://www.nuget.org/packages/MvvmValidation/2.1.0-beta
